# Generated by Django 5.0.3 on 2024-03-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_extraitem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemealprecancellation',
            name='is_precancelled',
        ),
        migrations.AddField(
            model_name='basemealprecancellation',
            name='time',
            field=models.CharField(default='Breakfast', max_length=20),
        ),
    ]
