# Generated by Django 5.0.3 on 2024-03-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_remove_basemealprecancellation_is_precancelled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemealprecancellation',
            name='student',
        ),
        migrations.AddField(
            model_name='basemealprecancellation',
            name='rollno',
            field=models.IntegerField(default=0),
        ),
    ]
