# Generated by Django 5.0.3 on 2024-03-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_remove_basemealprecancellation_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingextraitems',
            name='student',
        ),
        migrations.AddField(
            model_name='bookingextraitems',
            name='extra_item',
            field=models.CharField(default='DCBM', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingextraitems',
            name='rollno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingextraitems',
            name='time',
            field=models.CharField(default='Breakfast', max_length=20),
        ),
    ]
