# Generated by Django 5.0.2 on 2024-04-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_remove_bookingextraitems_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownchartextra',
            name='extra_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.bookingextraitems'),
        ),
    ]
