# Generated by Django 5.0.3 on 2024-04-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_manager', '0004_delete_extramealmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmenu',
            name='breakfast',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='dinner',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='lunch',
            field=models.CharField(max_length=150),
        ),
    ]
