# Generated by Django 5.0.3 on 2024-04-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_manager', '0005_alter_messmenu_breakfast_alter_messmenu_dinner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messmenu',
            name='price',
        ),
    ]
