# Generated by Django 5.0.2 on 2024-04-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_manager', '0006_remove_messmenu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemealcharge',
            name='min_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
